[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.8.0,<3"
torchvision = ">=0.24.0,<0.25"
torchaudio = ">=2.8.0,<3"
torch-geometric = ">=2.6.1,<3"
ogb = ">=1.3.6,<2"
ipykernel = ">=7.1.0,<8"
